ARG BASE_CONTAINER=duplocloud/anyservice:spark_3_2_ia_v1
FROM $BASE_CONTAINER


WORKDIR /home/centos
USER root

HEALTHCHECK CMD curl -f http://localhost:8998/ || exit 1

ENV LIVY_VERSION=0.8.0-incubating
#ENV LIVY_CONF_DIR=/etc/livy
ENV LIVY_CONF_DIR=/opt/livy/conf
ENV LIVY_LOG_DIR=/var/log/livy
ENV LIVY_LOG_FILE=/var/log/livy/livy--server.out
ENV LIVY_HOME /opt/livy
#ENV LIVY_URL https://archive.apache.org/dist/incubator/livy/$LIVY_VERSION/apache-livy-$LIVY_VERSION-bin.zip
ENV LIVY_URL https://dlcdn.apache.org/incubator/livy/${LIVY_VERSION}/apache-livy-${LIVY_VERSION}-bin.zip
#            https://dlcdn.apache.org/incubator/livy/0.7.1-incubating/apache-livy-0.7.1-incubating-bin.zip
ENV PATH $LIVY_HOME/bin:$PATH

WORKDIR /opt
#apache-livy-0.7.1-incubating-bin

#RUN curl -fSL $LIVY_URL -o /tmp/livy.zip \
#      && unzip /tmp/livy.zip \
#      && mv /opt/apache-livy-$LIVY_VERSION-bin /opt/livy-$LIVY_VERSION \
#      && ls -al \
#      && rm /tmp/livy.zip \
#      && cd

#RUN cd /tmp && curl -fSL $LIVY_URL -o livy.zip \
#      && unzip livy.zip  -d /tmp \
#      && mv apache-livy-$LIVY_VERSION-bin /opt/livy-$LIVY_VERSION \
#      && ls -al \
#      && cd \
#      && ln -s /opt/livy-$LIVY_VERSION $LIVY_HOME \
#      && ls -altR /opt/livy


#RUN yum install -y git curl
#ARG MAVEN_VERSION=3.6.3
#ARG USER_HOME_DIR="/root"
#ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries
#
#
#RUN mkdir -p /opt/maven /opt/maven/ref
#RUN echo ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz
#RUN curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz
#RUN tar -xzf /tmp/apache-maven.tar.gz -C /opt/maven --strip-components=1
#RUN rm -f /tmp/apache-maven.tar.gz
#RUN ln -s /opt/maven/bin/mvn /usr/bin/mvn
#
##RUN mkdir -p /opt/maven /opt/maven/ref \
## && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
## && tar -xzf /tmp/apache-maven.tar.gz -C /opt/maven --strip-components=1 \
## && rm -f /tmp/apache-maven.tar.gz \
## && ln -s /opt/maven/bin/mvn /usr/bin/mvn
#
#ENV MAVEN_HOME /opt/maven
#ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"
WORKDIR /build
RUN git clone https://github.com/apache/incubator-livy.git
WORKDIR   /build/incubator-livy

RUN cp -rf /build/incubator-livy/conf  /build/incubator-livy/conf.origin
#COPY ./base-pom.xml /build/incubator-livy/pom.xml
#COPY ./python-api-pom.xml /build/incubator-livy/python-api/pom.xml



COPY ./0.8/pom.xml /build/incubator-livy/pom.xml
COPY ./0.8/python-api/pom.xml /build/incubator-livy/python-api/pom.xml
COPY ./0.8/assembly/pom.xml /build/incubator-livy/assembly/pom.xml
COPY ./0.8/coverage/pom.xml /build/incubator-livy/coverage/pom.xml

COPY conf/*  /build/incubator-livy/conf/

RUN mvn clean package -B -V -e \
        -Pspark-3.0 \
        -Pthriftserver \
        -DskipTests \
        -DskipITs \
        -Dmaven.javadoc.skip=true

# copied form emr 6.5.0 livvy 0.71
RUN cd /build/incubator-livy/assembly/target && \
     unzip apache-livy-0.8.0-incubating-SNAPSHOT-bin.zip && \
     mv apache-livy-0.8.0-incubating-SNAPSHOT-bin /opt/livy
#RUN mv /build/incubator-livy /opt/livy
RUN rm -rf /build/incubator-livy
RUN chmod -R +x /opt/livy
RUN chmod +x /opt/livy/bin/livy-server

RUN ls -alt /opt/
RUN ls -alt /opt/livy

RUN mkdir -p $LIVY_LOG_DIR && touch $LIVY_LOG_FILE   && ln -sf /dev/stdout $LIVY_LOG_FILE


COPY requirements.txt .
RUN pip install -r requirements.txt

WORKDIR /home/centos
#RUN cp  -r $LIVY_HOME/conf $LIVY_HOME/conf-origin
#COPY livy.conf $LIVY_CONF_DIR/livy.conf
#COPY livy-env.sh  $LIVY_CONF_DIR/livy-env.sh

COPY *.sh ./
RUN chmod +x *.sh

#USER centos


CMD ["/bin/bash", "/home/centos/statup-livy.sh"]
