global:
  scrape_interval: 5s
  evaluation_interval: 5s
#rule_files:
#  - /etc/prometheus/prometheus.rules
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      #- "alertmanager.monitoring.svc:9093"
scrape_configs:


  - job_name: 'proetheus-new-3'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'kube-state-metrics-new-3'
    scheme: https
    static_configs:
      - targets: ['10.96.11.13:443']

  - job_name: 'cadvisor1-new-3'
    static_configs:
      - targets: ['10.96.102.116:8080']
  - job_name: 'node-exporter-new-3'
    scheme: https
    static_configs:
      - targets: ['10.96.225.71:9100']
